### ISSUE TITLE
What's about self-hosted Stable Diffusion?

### ISSUE THREAD

**Issue by sebaxakerhtc** [nextcloud/integration_replicate#1]
Hi!
That works nice!
Not an issue with replicate.
I want to know, can we use self-hosted stable diffusion? (like the [best one](https://github.com/AUTOMATIC1111/stable-diffusion-webui) )
I used their [API](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/API) in different applications including [discord bot](https://github.com/Kilvoctu/aiyabot) and i want to be free from any external AI platforms with their restrictions and impossibilites.
So... my nextcloud, my server, my hardware, my Stable Diffusion. :)
Thank you!

**Comment by julien-nc** [comment]
Hey, thanks for the suggestion. This would be awesome indeed. Would you be interested in implementing this integration? We could give you hints and examples during the development.

**Comment by DaphneMuller** [comment]
hey @sebaxakerhtc , nice to e-meet you! My name is Daphne, I'm an engineering team lead at Nextcloud. I was curious, have you considered to continue your idea? 

The reason I'm reaching out is we would love to see this implemented as part of the release end of this year. If you're still up for some development in this area, maybe I can support you, for example, I could offer you a 1:1 call with a senior developer from my team to answer any questions you may have and to review the work, if that would be helpful for you. Let me know :)

**Comment by sebaxakerhtc** [comment]
Hello @DaphneMuller and thank you for your attention.
I'm not a PHP-dev. I can understand the whole code and edit it like I need, but not to create a project from zero.
But, yeah, if I'll have some examples and hints - I can try to create this wonderful app

**Comment by DaphneMuller** [comment]
@sebaxakerhtc thank you for your fast and enthusiastic reply ❤️ how would you like to proceed, shall I make a chat room for quick questions with a dev, or schedule a call between you and a dev to get you started, or something else?

**Comment by sebaxakerhtc** [comment]
@DaphneMuller I think a chat room will be better, because I can send some questions and dev will reply when he/she will have a time.

**Comment by DaphneMuller** [comment]
@sebaxakerhtc will do! the person I have in mind will be back from holiday tomorrow, I will first discuss it 1:1 and then send you a link tomorrow.

**Comment by marcelklehr** [comment]
Ahoy @sebaxakerhtc :wave:
I invite you to join me at https://cloud.nextcloud.com/call/8529065042 to work on this together :)

**Comment by marcelklehr** [comment]
hi @sebaxakerhtc I'm currently working on designing the server (OCP) API for text2image providers, if you would like to have a look, PR is here https://github.com/nextcloud/server/pull/40326 :blue_heart:

**Comment by marcelklehr** [comment]
Hello @sebaxakerhtc 
I'm sorry for the delay on this. The OCP API has been finalized now and is ready to be implemented. The new docs for it are currently in review, but you can already check them out here: https://github.com/nextcloud/documentation/pull/11248
