### ISSUE TITLE
Contrary Ethical AI Rating

### ISSUE THREAD

**Issue by FlyingP1g** [nextcloud/integration_replicate#12]
AI rating in [readme](https://github.com/nextcloud/integration_replicate?tab=readme-ov-file) and in [Nextcloud apps store](https://apps.nextcloud.com/apps/integration_replicate) are different and confusing, especially in [Nextcloud apps store](https://apps.nextcloud.com/apps/integration_replicate).

**Comment by marcelklehr** [comment]
Should be fixed now. Thanks for reporting :)
