### ISSUE TITLE
How to use without third party?

### ISSUE THREAD

**Issue by LordOfTheRats** [nextcloud/integration_replicate#6]
The Nextcloud Hub 5 blog post promises, that all AI features can be used offline / without third parties.

![grafik](https://github.com/nextcloud/integration_replicate/assets/4635106/a1b9f1b6-c5c1-4685-9b0e-888b364bb03b)

How can I use this extension without an API key? Am I barking up the wrong tree?

I guess this is related to #1

**Comment by marcelklehr** [comment]
Hello @LordOfTheRats 

we were lagging behind on making available image generation for on-premise usage. It will be made available with Nextcloud 28. Thank you for your patience.
